--DROP TABLE IF EXISTS OrderPackage;
--DROP TABLE IF EXISTS [Order];
--DROP TABLE IF EXISTS Package;
--DROP TABLE IF EXISTS Business;
--DROP TABLE IF EXISTS [User];
--DROP TABLE IF EXISTS PackageType;
--DROP TABLE IF EXISTS BusinessType;
--DROP TABLE IF EXISTS Status;
--DROP TABLE IF EXISTS Role;

CREATE TABLE Role (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(50)
);

CREATE TABLE Status (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(50)
);

CREATE TABLE BusinessType (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(50)
);

CREATE TABLE PackageType (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(255)
);

CREATE TABLE [User] (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    RoleID UNIQUEIDENTIFIER,
    Email NVARCHAR(50) UNIQUE,
    Password NVARCHAR(50),
    Name NVARCHAR(100),
    FOREIGN KEY (RoleID) REFERENCES Role(ID)
);

CREATE TABLE Business (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(50),
    Description VARCHAR(1000),
    Address VARCHAR(100),
    ImageURL VARCHAR(1000),
    BusinessTypeID UNIQUEIDENTIFIER,
    FOREIGN KEY (BusinessTypeID) REFERENCES BusinessType(ID)
);

CREATE TABLE Package (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    BusinessID UNIQUEIDENTIFIER,
    PackageTypeID UNIQUEIDENTIFIER,
    Name NVARCHAR(50),
    Description NVARCHAR(1000),
    Price FLOAT,
    Quantity INT,
    PickupStart DATETIME,
    PickupEnd DATETIME,
    ImageURL VARCHAR(1000),
    FOREIGN KEY (BusinessID) REFERENCES Business(ID),
    FOREIGN KEY (PackageTypeID) REFERENCES PackageType(ID)
);

CREATE TABLE [Order] (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    BusinessID UNIQUEIDENTIFIER,
    StatusID UNIQUEIDENTIFIER,
    OrderNumber INT,
    FOREIGN KEY (UserID) REFERENCES [User](ID),
    FOREIGN KEY (BusinessID) REFERENCES Business(ID),
    FOREIGN KEY (StatusID) REFERENCES Status(ID)
);

CREATE TABLE OrderPackage (
    OrderID UNIQUEIDENTIFIER,
    PackageID UNIQUEIDENTIFIER,
    Quantity INT,
    PRIMARY KEY (OrderID, PackageID),
    FOREIGN KEY (OrderID) REFERENCES [Order](ID),
    FOREIGN KEY (PackageID) REFERENCES Package(ID)
);
